// Compiles the web-adapted NetLogo model and the reporters the web UI reads.
// Output goes to public/sim/, which the browser worker and the Node tests load.
import fs from "node:fs";
import vm from "node:vm";
vm.runInThisContext(
  fs.readFileSync("simulation-runtime/tortoise-compiler.js", "utf8"),
);
const compiler = new BrowserCompiler();
const result = compiler.fromNlogoXML(
  fs.readFileSync("simulation-runtime/model.nlogox", "utf8"),
);
if (!result.model.success) throw new Error(JSON.stringify(result.model.result));
fs.mkdirSync("public/sim", { recursive: true });
fs.writeFileSync("public/sim/model.js", result.model.result);

// Rates use the same formula as export-link-results in the desktop model.
const hours = "(max list (1 / 3600) (measured-seconds / 3600))";
const expressions = {
  metrics:
    "(list ticks count cars generated-total completed-total stranded-count queued-at-gates mean-trip-time-min mean-delay-min measured-seconds trips-done vehicle-hours run-finished? closure-desc selection-label measuring? (is-list? baseline-signature) (baseline-signature = scenario-signature) baseline-summary selected-street selected-block warm-up-s measure-s)",
  cars: "[ (list who xcor ycor heading color) ] of cars",
  roads:
    "map [L -> [(list [who] of end1 [who] of end2 street seg geometry lanes road-kind direction-name cars-allowed?)] of L] sort roads",
  styles:
    "map [L -> [(list color thickness closed? lanes-open win-count base-count tt-ema (closed? or (partner != nobody and [closed?] of partner)) (lanes-open < lanes or (partner != nobody and [lanes-open < lanes] of partner)))] of L] sort roads",
  nodes:
    '[ (list xcor ycor node-kind label) ] of nodes with [node-kind != "grid"]',
  labels: "[ (list xcor ycor label) ] of map-labels",
  bounds: "(list min-pxcor max-pxcor min-pycor max-pycor)",
  csv: `map [L -> [(word "\\"" street "\\"," direction-name "," seg ",\\"" node-name end1 "\\",\\"" node-name end2 "\\"," lanes "," lanes-open "," closed? "," precision (win-count / ${hours}) 1 "," precision base-count 1 "," precision ((win-count / ${hours}) - base-count) 1 "," precision tt-ema 1)] of L] filter [L -> [cars-allowed? and road-kind != "access"] of L] sort roads`,
  baseline:
    "(list (ifelse-value is-list? baseline-signature [table:to-list baseline] [[]]) baseline-summary baseline-signature)",
  conservation:
    "generated-total = completed-total + stranded-count + count cars + queued-at-gates",
};
const compiled = [];
for (const [key, expression] of Object.entries(expressions)) {
  const out = compiler.compileReporter(expression);
  if (!out.success) throw new Error(`${key}: ${JSON.stringify(out)}`);
  compiled.push(
    `  ${JSON.stringify(key)}: function () {\n    return (${out.result});\n  }`,
  );
}
fs.writeFileSync(
  "public/sim/reporters.js",
  `// Generated by scripts/compile-model.mjs. Do not edit.\nself.TRAFFIC_REPORTERS = {\n${compiled.join(",\n")}\n};\n`,
);
console.log("Compiled the combined NetLogo model and web reporters.");

// Map previews let the page draw streets while the engine starts.
const { loadTrafficSim } = await import("../src/lib/engine.mjs");
for (const [key, network] of [
  ["osm", "Real OSM map"],
  ["schematic", "Schematic Hoddle grid"],
]) {
  const sim = loadTrafficSim();
  sim.set("network-source", network);
  const world = sim.setup();
  fs.writeFileSync(`public/network-${key}.json`, JSON.stringify(world));
}
console.log("Updated both map previews.");
